#include <stdio.h>
#include <stdlib.h>
#include <time.h>

void direct_addressing(double* x, double* y, double* scalar, size_t* n) {
	for (size_t i = 0; i < *n; i++) {
		y[i] += *scalar * x[i];
	}
}

void main() {

	clock_t begin = clock();

	size_t n = 1000000; size_t m = 1000;
	
	/*for (size_t kx = 0; kx < n; ++kx) {
	
		jx = p[kx];
		y[jx] += a * x[jx];		

	}*/
 	
	size_t* p = malloc(sizeof(size_t)*n);
 	double* x = malloc(sizeof(double)*n);
 	double* y = malloc(sizeof(double)*n);
  	
  	
	// benchmark it with some vectors x, and y, and a scalar a, and with p generated by either 	
	
	size_t ix = 0;
	for (size_t jx = 0; jx < m; ++jx)	
		for (size_t kx = 0; kx < m; ++kx)
			p[jx + m*kx] = ix++;
	
	// or

	/*for (ix = 0; ix < n; ++ix)
		p[ix] = ix;*/
	double scalar = 4;
	direct_addressing(x, y, &scalar, &n);

	clock_t end = clock();
	double time_spent = (double)(end - begin) / CLOCKS_PER_SEC;
	printf("\n Time for program is :  %f \n");

}

